[package]
name = "arn"
version = "0.1.1"
edition = "2024"

[dependencies]
arrayvec = "0.7.6"
serde = { version = "1.0.219", features = ["derive"] }
strum = { version = "0.27.1", features = ["derive"] }
thiserror = "2.0.12"

[dev-dependencies]
serde_json = "1.0.140"
